### ISSUE TITLE
Checking for updates stuck

### ISSUE THREAD

**Issue by IamcomingfromJUPITER** [LegacyUpdate/LegacyUpdate#129]
I installed Legacy Update into Windows XP Home Edition Service Pack 3, but it stuck at checking for updates. Checking for the latest updates for your computer... This goes forever. The network icon at the taskbar does not flashes so it means there is no networking going on. How do I fix this? I need to update but I can't!!! Can someone help me?

**Comment by kirb** [comment]
Going to close this because it's an incredibly old thread (sorry I never responded...). Did you have Office installed? If so, there's a [workaround](https://msfn.org/board/topic/184136-fix-windows-update-stuck-on-checking-for-updates-on-vista-and-xp-well-kinda-after-installing-office-2010-sp2/) for this issue. Otherwise, our [FAQ](https://legacyupdate.net/faq/issues) page might help. If you're still having issues, you can make a thread in the Discussions tab here, or [Discord](https://legacyupdate.net/discord).
