### ISSUE TITLE
Remove kb905474 & KB2934207 from Windows XP update selection

### ISSUE THREAD

**Issue by tranquilcarbon** [LegacyUpdate/LegacyUpdate#193]
kb905474 & KB2934207 for those who do not know are two redundant updates for Windows XP.

kb905474 used to install the WGA notifications software which reported if the software is "Legitimate", however, i think the servers required no longer exist or the update is broken, plus the update is redundant due to the fact legacy update already has activation support. (Note that i am not supporting piracy, it's just that this update is redundant since most installations will report as illegitimate)

In addition, KB2934207 is the windows XP EOL notification, i think this update should be removed from the update selections since i think most Windows XP Users know that the OS has reached EOL.

**Comment by andika207** [comment]
most installations...most users... LOL talk for yourself !

the EOL message is very simple to skip and you have do it 1 time forever and it's part of XP history

regarding the WGA notification that mostly concerns those who don't have a genuine ISO or use modiffied crap

**Comment by kirb** [comment]
Unlikely to do this, so closing.

In the case of the WGA updates, I don't feel it's right to mess with them. Either way, apps that demand to have a genuine install will refuse to run. If the update is installed it'll fail because of server issues; if not it'll force you to install it. The current config seems to work fine, and mandatory WGA checks were discontinued around XP SP3 anyway, so I don't think I'll change this.

The EOL notice is an optional update, so you can choose to ignore it, or just select to not show it again when the dialog shows up. I try to prefer having Legacy Update replicate exactly what you would have seen when Windows Update still officially worked, and I don't think this needs to have an exception. It's also tiny, so the overhead of having it installed isn't a big deal.
