### ISSUE TITLE
Adding KB3102810 for Windows 7

### ISSUE THREAD

**Issue by usefulstuffs** [LegacyUpdate/LegacyUpdate#232]
This update is required for the WU agent to work properly on 7, else it gives 80072EFE. But it is not integrated in Legacy Update Setup. Can you add it? Thanks!

**Comment by stdin82** [comment]
No it's not needed
and it's superseded

**Comment by w32u** [comment]
I guess I've recreated the situation where you need to install KB3102810 for getting Windows Update on Windows 7 to work:

1) Install the two SHA2 updates on the clean Windows 7 installation, [KB4490628](https://support.microsoft.com/help/4490628) and [KB4474419](https://support.microsoft.com/help/4474419) (for example I need them because AMD graphics driver for my GPU was released in 2022 and thus requires these updates)
2) Install LegacyUpdate
3) Check for updates in WU, you'll get a 80072EFE error:
![step1](https://github.com/user-attachments/assets/87fbed27-efd9-43a2-868c-146df2466efa)
4) Install [KB3102810](http://support.microsoft.com/kb/KB3102810) and reboot
5) Check for updates again
![step2](https://github.com/user-attachments/assets/5d9d5dde-0496-466a-a687-10629cff5e08)

I guess LegacyUpdate should check if SHA2 updated have already been installed, and if it's true, KB3102810 will need to be installed

**Comment by kirb** [comment]
Fixed in Legacy Update 1.10
