### ISSUE TITLE
SSL Certificate invalid (Cloudflare).

### ISSUE THREAD

**Issue by mikedebian** [LegacyUpdate/LegacyUpdate#246]
Just got this today when attempting to search for updates.

"The SSL certificate presented by the server did not pass validation. This could indicate an expired SSL certificate or a certificate that does not include the requested domain name. Please contact your hosting provider to ensure that an up-to-date and valid SSL certificate issued by a Certificate Authority is configured for this domain name on the origin server. [Additional troubleshooting information here.](https://support.cloudflare.com/hc/en-us/articles/200721975)"

**Comment by mikedebian** [comment]
I did not have to. It fixed itself today. I don't think it was a cache issue.

**Comment by kirb** [comment]
Thanks for reporting and sorry this happened, fixed about 8 hours ago.

I migrated Legacy Update to a new server ... probably 90 days ago now considering how long Let's Encrypt certificates last, and didn't migrate the certbot configuration properly. Fixed now so it shouldn't be an issue going forward.

Since some mentioned using Cloudflare's edge certificates which have an extremely long validity - I prefer using Let's Encrypt anyway so keys are rotated every 90 days (usually less than that). LE uses short expiry periods to ensure you're rotating keys often, not only once a year or effectively never. Not that we're currently doing much that can be compromised by a lack of transport security, updates themselves must still be signed by Microsoft, but I'd rather be doing it than not.
