### ISSUE TITLE
Activation check doesn’t work on Windows XP/Server 2003 x64

### ISSUE THREAD

**Issue by kirb** [LegacyUpdate/LegacyUpdate#263]
We use licdll.dll’s COM class directly, but only a 64-bit build of it exists on Server 2003 x64. As we’re 32-bit, we can’t load it, which means the activation option won't appear.

**Comment by renodr** [comment]
I haven't had a chance to test this yet, but can we use CLSCTX_ACTIVATE_64_BIT_SERVER (rather than CLSCTX_INPROC_SERVER) in the CoCreateInstance if we do a check to determine if we're on a 64-bit system? We've done this before when activating the correct version of LegacyUpdate in Internet Explorer on 64-bit XP/2003.

I'll give this a shot once I'm done with the CI stuff.

**Comment by renodr** [comment]
![image](https://github.com/user-attachments/assets/f3e824b8-f56f-4d9b-893f-d69346eeac40)

I got the activation check working on XP x64! I'll submit a PR after I've let it run through the rest of the LegacyUpdate setup process.

**Comment by renodr** [comment]
Here's a patch containing what I've been able to come up with so far! I'll hopefully be able to look at this again in a little while
[winxp-server2k3-x64-activation-fix.patch](https://github.com/user-attachments/files/17439790/winxp-server2k3-x64-activation-fix.patch)

I keep running into crashes when installing the updates though

**Comment by renodr** [comment]
It appears the issue with crashes was fixed during one of the subsequent commits, though I'm not sure which one from a first glance.

![image](https://github.com/user-attachments/assets/4f9b56f2-fbe2-4fee-abb4-dfde4afbe52d)

Going to submit this as a PR shortly, as well as a fix for #296
