### ISSUE TITLE
Fix for chart tooltip flickering + Report for broken fallback method

### ISSUE THREAD

**Issue by Kiki79250CoC** [LegacyUpdate/LegacyUpdate#267]
Hi,

I don't really know if it's the most appropriate place to post this but since it's the project repo, I think it still worth posting this here.

So this issue is more to provide a fix to the chart tooltip' flickering issue that's kinda annoying.
After studying a bit how it's displayed, I created a small piece of CSS that seems to fix that issue for good.

As those charts are not displayed on IE, I think trying to make a fix for those browsers is pointless so I'll only provide the fix for the "other" browsers (even if this fix should also work on IE11 only (as IE10 and earlier doesn't support the `pointer-events` rule)).

```css
.google-visualization-tooltip,
svg g path[stroke="#636363"],
svg g path[stroke="#636363"] + circle {
    pointer-events: none;
}
```

Here's a GIF showing the fix in action:
![Flickerfix](https://github.com/user-attachments/assets/c75ccfe3-0ae9-4d69-b564-700b03d0b90d)

About the CSS code itself, I had to compose with the limitations of the lack of distinct names in the rendered SVG itself, but it should not disrupt anything in the page.

--

(Also this can be the occasion to point out the fact the image-based fallback rendering is broken and displays nothing, a look inside the "image" reports a 404 error)

![image](https://github.com/user-attachments/assets/e3d93de0-b7f0-4466-917a-67611be740e6)

**Comment by kirb** [comment]
Thanks heaps for looking into this! This is a really well-written report, and the gif was a good idea 😊

Google finally discontinued the old server-rendered charts API (which they announced would be shut down in 2019, then mysteriously it didn't go away for another 4 years, lol). I put off fixing it since I figured I'd have to find a different charts service or a library, and libraries I tried in the past kinda didn't look amazing. I did find [quickchart.io](https://quickchart.io/), which looks great, so I just switched the prerendered charts to that. They should be live now.

I might switch the JS charts to quickchart too, because it just looks better overall in terms of being maintained, which I really don't trust Google with these days. I like the 3D pie and the legend with connecting lines + speech-bubble tooltips, but, well, it's Google, and this bug has existed in Google Charts at least since we started using it.
