### ISSUE TITLE
[Question] Can you add parameters for silent install?

### ISSUE THREAD

**Issue by hasanmerkit** [LegacyUpdate/LegacyUpdate#313]
While waiting for the new version for Audit(Sysprep) mode, I thought about the silent or unattended installation feature.

Can unattended installation parameters be added? Example: /silent /passive /noactivewindows

I also install the necessary updates for Legacy Update with CMD before starting the installation. I found the certificates in the %ProgramData%\LegacyUpdate folder and copied them. However, I could not find how to install them with CMD.

(Sorry for my bad English, Translate and AI used.)

**Comment by i13k** [comment]
Please refer to [this link](https://legacyupdate.net/faq/automation) for more information on Legacy Update silent/passive installation.

**Comment by kirb** [comment]
For the root certs updates, you can find the commands used [here](https://github.com/LegacyUpdate/LegacyUpdate/blob/06088da68da0826a5ecb82eb78c1ccc000a785d6/setup/UpdateRoots.nsh#L71-L75). The flags specify which certificate store they get installed to. updroots.exe can be found with [these instructions](https://github.com/LegacyUpdate/LegacyUpdate/blob/v1.10.0.0/README.md#building). Note that this won't fully replicate what Legacy Update does, as we also update SSL settings in the registry (that logic can be found in the same file). 1.10.1 is also moving root cert updating from the external updroots.exe to some built-in logic, since this gives us better control over it, but overall it's still doing the same thing.

I think this is all addressed so closing this, but feel free to reply here still.
